name: Algolia Upload Records
on:
  [push]
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: tilburgsciencehub/algolia-uploader@master
        with:
          app_id: ${{secrets.APPLICATION_ID}}
          admin_key: ${{secrets.ADMIN_API_KEY}}
          index_name: ${{secrets.INDEX_NAME}}
          index_file_path: ${{secrets.FILE_PATH}}
