name: Algolia Upload Records
on:
  [push]
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{secrets.APPLICATION_ID}}
          algolia_api_key: ${{secrets.ADMIN_API_KEY}}
          file: ${{secrets.FILE_PATH}}